import Navbar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";

import { Roboto } from "next/font/google";
const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "NewsNetGoal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" ">
      <body className={roboto.className}>
        <main className=" text-textPrimary   ">
          <Navbar />

          <section className="">{children}</section>
        </main>
      </body>
    </html>
  );
}
